version: "3"
services:
  webserver:
    image: nginx:alpine
    container_name: webapp-nginx
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
