version: '3'
services:
  db:
    image: postgres
    container_name: posgres_db
    restart: always
    env_file:
      - .env
    networks:
      - my-pg-network
    ports:
      - 5432:5432

networks:
  my-pg-network:
    driver: bridge
